In [3]:
import pandas as pd

In [6]:
path = "./2017_arrest_motivation.csv"
df = pd.read_csv(path, skiprows=5)
df

     Precinct  Number  Gender   Race   Age      Bias Motivation
0         1.0     1.0    Male  White  40.0  Anit-Other Religion
1         NaN     2.0    Male  Black  29.0           Anti-White
2         6.0     3.0    Male  White  48.0           Anti-Asian
3         NaN     4.0    Male  White  32.0            Anti-LGBT
4         NaN     5.0    Male  White  59.0           Anti-Black
..        ...     ...     ...    ...   ...                  ...
131       NaN   132.0    Male  Black  20.0            Anti-LGBT
132     121.0   133.0    Male  White  57.0        Anti-Hispanic
133     122.0   134.0  Female  White  44.0           Anti-Black
134     123.0   135.0    Male  White  37.0          Anti-Jewish
135       NaN     NaN     NaN    NaN   NaN                  NaN

[136 rows x 6 columns]