In [2]:
import pandas as pd
import os
import re

In [6]:
path = "/Users/savannahestridge/Desktop/NYC_hate_crimes/arrest_by_bias/2018/2018_arrest_motivation.csv"

df = pd.read_csv(path, skiprows=5)
df

,Number,Precinct,Gender,Race,Age,Bias-Motivation,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,1.0,Male,Black,24,Anti-Jewish,NaN,NaN,NaN,NaN,NaN
1,2,NaN,Male,Black,24,Anti-Jewish,NaN,NaN,NaN,NaN,NaN
2,3,NaN,Male,Black,24,Anti-Jewish,NaN,NaN,NaN,NaN,NaN
3,4,NaN,Male,Black,24,Anti-Jewish,NaN,NaN,NaN,NaN,NaN
4,5,NaN,Female,Black,37,Anti-White,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
145,146,NaN,Male,Asian,57,Anti-male homosexual (Gay),NaN,NaN,NaN,NaN,NaN
146,147,115.0,Male,White,55,Anti-Black,NaN,NaN,NaN,NaN,NaN
147,148,120.0,Male,Black,14,Anti-White,NaN,NaN,NaN,NaN,NaN
148,149,122.0,Male,White,33,Anti-Black,NaN,NaN,NaN,NaN,NaN
149,150,NaN,Male,White,26,Anti-Black,NaN,NaN,NaN,NaN,NaN

In [7]:
df = df[['Number', 'Precinct', 'Gender', 'Race', 'Age', 'Bias-Motivation']]
df

     Number  Precinct  Gender   Race  Age             Bias-Motivation
0         1       1.0    Male  Black   24                 Anti-Jewish
1         2       NaN    Male  Black   24                 Anti-Jewish
2         3       NaN    Male  Black   24                 Anti-Jewish
3         4       NaN    Male  Black   24                 Anti-Jewish
4         5       NaN  Female  Black   37                  Anti-White
..      ...       ...     ...    ...  ...                         ...
145     146       NaN    Male  Asian   57  Anti-male homosexual (Gay)
146     147     115.0    Male  White   55                  Anti-Black
147     148     120.0    Male  Black   14                  Anti-White
148     149     122.0    Male  White   33                  Anti-Black
149     150       NaN    Male  White   26                  Anti-Black

[150 rows x 6 columns]

In [8]:
df.dtypes

Number               int64
Precinct           float64
Gender              object
Race                object
Age                  int64
Bias-Motivation     object
dtype: object

In [27]:
print(df1.head(20))

    Number  Precinct  Gender   Race  Age             Bias-Motivation
0        1       1.0    Male  Black   24                 Anti-Jewish
1        2       NaN    Male  Black   24                 Anti-Jewish
2        3       NaN    Male  Black   24                 Anti-Jewish
3        4       NaN    Male  Black   24                 Anti-Jewish
4        5       NaN  Female  Black   37                  Anti-White
5        6       NaN    Male  White   35                 Anti-Jewish
6        7       NaN    Male  White   35                 Anti-Jewish
7        8       5.0    Male  Black   29  Anti-male homosexual (Gay)
8        9       NaN    Male  White   57                  Anti-Black
9       10       6.0  Female  White   58            Anti-Transgender
10      11       NaN    Male  White   44  Anti-male homosexual (Gay)
11      12       NaN    Male  White   47       Anti-Islamic (Muslim)
12      13       NaN    Male  White   35                 Anti-Jewish
13      14       7.0    Male  White   37                  Anti-Black
14      15       9.0    Male  Black   42       Anti-Islamic (Muslim)
15      16       NaN    Male  White   58                 Anti-Jewish
16      17      10.0    Male  Black   49       Anti-Islamic (Muslim)
17      18       NaN    Male  Black   24                 Anti-Jewish
18      19      13.0    Male  Black   53  Anti-male homosexual (Gay)
19      20       NaN    Male  Black   47               Anti-Hispanic

In [9]:
#remove decimal points from Precinct column

df['Precinct'] = df['Precinct'].astype(int).apply(lambda x: x.replace('.0',''))

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer